services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8003:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend