# Generated by Django 5.2.8 on 2026-02-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0003_itemhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemHistory",
        ),
    ]
