# Generated by Django 5.2.8 on 2026-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_delete_itemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmovementrequest',
            name='status',
            field=models.CharField(choices=[('WAITING_APPROVAL', 'Waiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED_UNVERIFIED', 'Completed Unverified')], default='WAITING_APPROVAL', max_length=20),
        ),
    ]
