# Generated by Django 5.2.8 on 2026-03-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0004_delete_itemhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmovementrequest",
            name="review_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("APPROVED", "Approved")], default="PENDING", max_length=10
            ),
        ),
    ]
