# Generated by Django 5.2.8 on 2026-04-02 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_collectionitem_is_verified'),
        ('movements', '0005_alter_itemmovementrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmovementrequest',
            name='from_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_requests_from', to='inventory.box'),
        ),
        migrations.AddField(
            model_name='itemmovementrequest',
            name='to_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_requests_to', to='inventory.box'),
        ),
        migrations.CreateModel(
            name='BoxMovementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING_APPROVAL', 'Waiting Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED_UNVERIFIED', 'Completed Unverified')], default='WAITING_APPROVAL', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_movement_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_movement_requests', to='inventory.box')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_movement_requests_from', to='inventory.location')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_movement_requests_created', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_movement_requests_to', to='inventory.location')),
            ],
            options={
                'db_table': 'box_movement_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='box_movemen_status_13cfa0_idx'), models.Index(fields=['box'], name='box_movemen_box_id_b4b340_idx')],
            },
        ),
    ]
