# Generated by Django 5.2.8 on 2025-11-12 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmovementrequest",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved/rejected",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movement_requests_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemmovementrequest",
            name="from_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="movement_requests_from", to="inventory.location"
            ),
        ),
        migrations.AddField(
            model_name="itemmovementrequest",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="movement_requests", to="inventory.collectionitem"
            ),
        ),
        migrations.AddField(
            model_name="itemmovementrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movement_requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemmovementrequest",
            name="to_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="movement_requests_to", to="inventory.location"
            ),
        ),
        migrations.AddIndex(
            model_name="itemmovementrequest",
            index=models.Index(fields=["status", "created_at"], name="item_moveme_status_ef3594_idx"),
        ),
        migrations.AddIndex(
            model_name="itemmovementrequest",
            index=models.Index(fields=["item"], name="item_moveme_item_id_6818e0_idx"),
        ),
    ]
