# Generated by Django 5.2.8 on 2025-11-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("box_code", models.CharField(help_text="Scannable code", max_length=100, unique=True)),
                ("label", models.CharField(blank=True, help_text="Human-friendly label", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Boxes",
                "db_table": "boxes",
                "ordering": ["box_code"],
            },
        ),
        migrations.CreateModel(
            name="ItemHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("MOVE_REQUESTED", "Move Requested"),
                            ("MOVE_APPROVED", "Move Approved"),
                            ("MOVE_REJECTED", "Move Rejected"),
                            ("IN_TRANSIT", "In Transit"),
                            ("ARRIVED", "Arrived"),
                            ("VERIFIED", "Verified"),
                            ("LOCATION_CORRECTION", "Location Correction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Item histories",
                "db_table": "item_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="e.g., 'Shelf A1', 'Floor - Main Exhibit'", max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("FLOOR", "Floor"), ("STORAGE", "Storage"), ("EVENT", "Event"), ("OTHER", "Other")],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_code", models.CharField(help_text="Barcode / scanned code", max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("platform", models.CharField(blank=True, help_text="e.g., 'SNES', 'PS2'", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_public_visible", models.BooleanField(default=True, help_text="For public catalogue")),
                ("is_on_floor", models.BooleanField(default=False, help_text="Redundant but fast for queries")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.box",
                    ),
                ),
            ],
            options={
                "db_table": "collection_items",
                "ordering": ["-created_at"],
            },
        ),
    ]
