# Generated by Django 5.2.8 on 2025-11-12 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemhistory",
            name="acted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemhistory",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="history", to="inventory.collectionitem"
            ),
        ),
        migrations.AddField(
            model_name="itemhistory",
            name="movement_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_events",
                to="requests.itemmovementrequest",
            ),
        ),
        migrations.AddField(
            model_name="itemhistory",
            name="from_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_from",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="itemhistory",
            name="to_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_to",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="current_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="current_items", to="inventory.location"
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="boxes", to="inventory.location"
            ),
        ),
        migrations.AddIndex(
            model_name="itemhistory",
            index=models.Index(fields=["item", "created_at"], name="item_histor_item_id_a1a0cf_idx"),
        ),
        migrations.AddIndex(
            model_name="itemhistory",
            index=models.Index(fields=["event_type"], name="item_histor_event_t_c3c664_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["item_code"], name="collection__item_co_0ec579_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["is_on_floor"], name="collection__is_on_f_16940e_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["is_public_visible"], name="collection__is_publ_95b87b_idx"),
        ),
    ]
