# Generated by Django 5.2.8 on 2026-02-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
