# Generated by Django 5.2.8 on 2026-02-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_box_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='item_type',
            field=models.CharField(choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware')], default='SOFTWARE', max_length=20),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_TRANSIT', 'In Transit'), ('CHECKED_OUT', 'Checked Out'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='working_condition',
            field=models.BooleanField(default=True, help_text='Whether the item is in working condition'),
        ),
    ]
