# Generated by Django 5.2.8 on 2026-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_collectionitem_item_type_collectionitem_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="condition",
            field=models.CharField(
                choices=[("EXCELLENT", "Excellent"), ("GOOD", "Good"), ("FAIR", "Fair"), ("POOR", "Poor")],
                default="GOOD",
                help_text="Physical condition of the item",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="creator_publisher",
            field=models.CharField(blank=True, help_text="Creator or publisher of the item", max_length=255),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="date_of_entry",
            field=models.DateField(blank=True, help_text="Date the item was added to the collection", null=True),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="date_published",
            field=models.CharField(blank=True, help_text="Date published", max_length=50),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="hardware_type",
            field=models.CharField(blank=True, help_text="Type of hardware", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="is_complete",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No"), ("UNKNOWN", "Unknown")],
                default="UNKNOWN",
                help_text="Whether the item is complete with all parts",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="is_functional",
            field=models.CharField(
                choices=[("YES", "Yes"), ("NO", "No"), ("UNKNOWN", "Unknown")],
                default="UNKNOWN",
                help_text="Whether the item is functional (for hardware)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="isbn_catalogue_number",
            field=models.CharField(blank=True, help_text="ISBN or catalogue number", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="item_subtype",
            field=models.CharField(blank=True, help_text="Subtype for non-electronic items", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="manufacturer",
            field=models.CharField(blank=True, help_text="Manufacturer of the hardware", max_length=255),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="media_type",
            field=models.CharField(blank=True, help_text="Type of media (e.g., CD, Cartridge)", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="model_number",
            field=models.CharField(blank=True, help_text="Model number", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="publisher",
            field=models.CharField(blank=True, help_text="Publisher", max_length=255),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="release_year",
            field=models.CharField(blank=True, help_text="Year of release", max_length=20),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="serial_number",
            field=models.CharField(blank=True, help_text="Serial number", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="version_edition",
            field=models.CharField(blank=True, help_text="Version or edition", max_length=100),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="volume_number",
            field=models.CharField(blank=True, help_text="Volume number", max_length=50),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="year_manufactured",
            field=models.CharField(blank=True, help_text="Year manufactured", max_length=20),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="item_type",
            field=models.CharField(
                choices=[("SOFTWARE", "Software"), ("HARDWARE", "Hardware"), ("NON_ELECTRONIC", "Non-Electronic")],
                default="SOFTWARE",
                max_length=20,
            ),
        ),
    ]
