# Generated by Django 5.2.8 on 2026-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_collectionitem_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="needs_review",
            field=models.BooleanField(default=False, help_text="Flagged for admin review (e.g. imported from legacy CSV)"),
        ),
    ]
