# Generated by Django 5.2.8 on 2026-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_collectionitem_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='is_verified',
            field=models.BooleanField(default=True, help_text="Whether the item's current location has been verified by an admin"),
        ),
    ]
