# Generated by Django 5.2.8 on 2026-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_move_approval',
            field=models.BooleanField(default=False, help_text='If True, movement requests require admin approval before location updates'),
        ),
    ]
