# Generated by Django 5.2.8 on 2026-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_requires_move_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
