# Generated by Django 5.2.8 on 2026-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_volunteerapplication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed password set during application, used when account is created on approval', max_length=255),
        ),
    ]
